language: ruby
cache: bundler
sudo: false

rvm:
  - 2.2
  - 2.3.3
  - 2.4.1

branches:
  only:
  - master

bundler_args: --jobs 7 --without docs

script:
  - bundle exec rake style
  - bundle exec rake spec
